/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CollectionsIndexRouteImport } from './routes/collections.index'
import { Route as CollectionsIdRouteImport } from './routes/collections.$id'
import { Route as CollectionsIdIndexRouteImport } from './routes/collections.$id.index'
import { Route as CollectionsIdEditRouteImport } from './routes/collections.$id.edit'

const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CollectionsRoute,
} as any)
const CollectionsIdRoute = CollectionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CollectionsRoute,
} as any)
const CollectionsIdIndexRoute = CollectionsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CollectionsIdRoute,
} as any)
const CollectionsIdEditRoute = CollectionsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => CollectionsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/collections': typeof CollectionsRouteWithChildren
  '/collections/$id': typeof CollectionsIdRouteWithChildren
  '/collections/': typeof CollectionsIndexRoute
  '/collections/$id/edit': typeof CollectionsIdEditRoute
  '/collections/$id/': typeof CollectionsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/collections': typeof CollectionsIndexRoute
  '/collections/$id/edit': typeof CollectionsIdEditRoute
  '/collections/$id': typeof CollectionsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/collections': typeof CollectionsRouteWithChildren
  '/collections/$id': typeof CollectionsIdRouteWithChildren
  '/collections/': typeof CollectionsIndexRoute
  '/collections/$id/edit': typeof CollectionsIdEditRoute
  '/collections/$id/': typeof CollectionsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/collections'
    | '/collections/$id'
    | '/collections/'
    | '/collections/$id/edit'
    | '/collections/$id/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/collections' | '/collections/$id/edit' | '/collections/$id'
  id:
    | '__root__'
    | '/'
    | '/collections'
    | '/collections/$id'
    | '/collections/'
    | '/collections/$id/edit'
    | '/collections/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CollectionsRoute: typeof CollectionsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/': {
      id: '/collections/'
      path: '/'
      fullPath: '/collections/'
      preLoaderRoute: typeof CollectionsIndexRouteImport
      parentRoute: typeof CollectionsRoute
    }
    '/collections/$id': {
      id: '/collections/$id'
      path: '/$id'
      fullPath: '/collections/$id'
      preLoaderRoute: typeof CollectionsIdRouteImport
      parentRoute: typeof CollectionsRoute
    }
    '/collections/$id/': {
      id: '/collections/$id/'
      path: '/'
      fullPath: '/collections/$id/'
      preLoaderRoute: typeof CollectionsIdIndexRouteImport
      parentRoute: typeof CollectionsIdRoute
    }
    '/collections/$id/edit': {
      id: '/collections/$id/edit'
      path: '/edit'
      fullPath: '/collections/$id/edit'
      preLoaderRoute: typeof CollectionsIdEditRouteImport
      parentRoute: typeof CollectionsIdRoute
    }
  }
}

interface CollectionsIdRouteChildren {
  CollectionsIdEditRoute: typeof CollectionsIdEditRoute
  CollectionsIdIndexRoute: typeof CollectionsIdIndexRoute
}

const CollectionsIdRouteChildren: CollectionsIdRouteChildren = {
  CollectionsIdEditRoute: CollectionsIdEditRoute,
  CollectionsIdIndexRoute: CollectionsIdIndexRoute,
}

const CollectionsIdRouteWithChildren = CollectionsIdRoute._addFileChildren(
  CollectionsIdRouteChildren,
)

interface CollectionsRouteChildren {
  CollectionsIdRoute: typeof CollectionsIdRouteWithChildren
  CollectionsIndexRoute: typeof CollectionsIndexRoute
}

const CollectionsRouteChildren: CollectionsRouteChildren = {
  CollectionsIdRoute: CollectionsIdRouteWithChildren,
  CollectionsIndexRoute: CollectionsIndexRoute,
}

const CollectionsRouteWithChildren = CollectionsRoute._addFileChildren(
  CollectionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CollectionsRoute: CollectionsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
